### PR TITLE
Change to match the current MessagePack specification

### PR DESCRIPTION
**Pull request by phmarek**
Hi,

the MessagePack Spec has changed; these changes try to get the "correct" behaviour.

Sadly the Lisp-specific encodings (`CONS` etc.) are lost now; we'd have to discuss a new encoding for them.

### CODE REVIEW

**Comment by mbrezu** [comment]
Hello, thanks for the pull request. I don't have a CL setup handy anymore, but I see you've written tests, so I trust the implementation is OK.

I have one objection regarding the documentation: you mention the previous implementation extensions, then say that these can be implemented using the new extension mechanism. I can't quickly figure out how to do that, so maybe you should add an example to the documentaton (e.g. implementing a 'pure cons').

**Comment by phmarek** [comment]
Well, as soon as I provide an example, we might as well just provide new implementations for the few things here.

We need to decide on a mapping of `integer` to `type`; eg. `0` for a `CONS`, `1` for a `SYMBOL`, etc.
Then we can encode the "real" data (eg. the `CAR` and the `CDR`) using messagepack mechanisms (eg. as an array with 2 elements), and use the bytes with the extended type encoding and our decided type number.

TBH, I would like to avoid that, at least for now. Using MessagePack to do RPC to other programs (I'm using it for NeoVim) doesn't have to provide the Lisp-specific things right now, and as soon as someone pops up who needs this perhaps a link to this pull request is sufficient to get a pull request ;)

**Comment by mbrezu** [comment]
Fair enough. :-)

On Fri, Jan 16, 2015 at 9:48 AM, phmarek <notifications@github.com> wrote:

> Well, as soon as I provide an example, we might as well just provide new
> implementations for the few things here.
>
> We need to decide on a mapping of integer to type; eg. 0 for a CONS, 1
> for a SYMBOL, etc.
> Then we can encode the "real" data (eg. the CAR and the CDR) using
> messagepack mechanisms (eg. as an array with 2 elements), and use the bytes
> with the extended type encoding and our decided type number.
>
> TBH, I would like to avoid that, at least for now. Using MessagePack to do
> RPC to other programs (I'm using it for NeoVim) doesn't have to provide the
> Lisp-specific things right now, and as soon as someone pops up who needs
> this perhaps a link to this pull request is sufficient to get a pull
> request ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbrezu/cl-messagepack/pull/3#issuecomment-70218802>.
>



-- 
Miron Brezuleanu

**Comment by mbrezu** [comment]
Apparently there's a problem with your changes. I got this email from Zach Beane:

I get this:

; caught ERROR:
;   READ error during COMPILE-FILE: The symbol "ID" is not external in the MESSAGEPACK package.
Longer log here: http://report.quicklisp.org/2015-01-20/failure-report/cl-messagepack.html

I don't have a CL install nearby, can you please take a look at this problem?

Thanks!

**Pull request merged**
